# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77cb454fa95152ae2cf04121e94668e5b44f3d0a454113af9e7d51de58a7cd60d1cb4f6d83b925f8e810b18f781258474a17e6c9f66b8432bca2cdbd7a30f896

test:
  secret_key_base: 2e3a250d2560a55b4c5982c75a306e0d6e59eb2f4bf6044aee98eea308093428b329fbaeb9517ba89574a37f0446b1d1402cd391c07fa3b2dee9af09771214c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
